version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    volumes:
      - postgres-eidiya2:/var/lib/postgresql/data

volumes:
  postgres-eidiya2:

#to run docker-compose.dev.yml
#docker-compose -f docker-compose.dev.yml up
# connection string: postgres://user:pass@localhost:6543/postgres